### PR TITLE
Adds the ability to save and load user scripts.

### PR DESCRIPTION
**Pull request by YveIce**
Adds the missing feature of saving and loading user-scripts. 
image

### CODE REVIEW

**Comment by Heath123** [comment]
Thanks

**Comment by Heath123** [comment]
Int he future it might also be nice to have it edit the file in place like a text editor

**Comment by YveIce** [comment]
Do you mean with 'in-place', when a script-file is opened, that you can just save it, with out choosing the path again? Aka overwriting?

**Comment by Heath123** [comment]
Yes

**Pull request merged**
